#config_version=5

hardware:
  platform: p_roc
  driverboards: sternWhitestar

displays:
  window:  # on screen window
    width: 600
    height: 200
  dmd:  # source display for the DMD
    width: 128
    height: 32
    default: true

window:
  width: 600
  height: 200
  title: Mission Pinball Framework
  source_display: window

slides:
  window_slide_1:  # slide we'll show in the on-screen window
  - type: display
    width: 512
    height: 12
  - type: text
    text: MISSION PINBALL FRAMEWORK
    anchor_y: top
    y: top-3
    font_size: 30
  - type: rectangle
    width: 514
    height: 130
    color: 444444
  dmd_slide_1:  # slide we'll show on the physical DMD
  - type: text
    text: IT WORKS!
    font_size: 30

slide_player:
  init_done:
    window_slide_1:
      target: window
    dmd_slide_1:
      target: dmd

dmds:
  my_dmd:
    shades: 16
    source_display: dmd
    platform: p_roc

p_roc:
  debug: true
  file_log: full
